version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_dc_passwd
    volumes:
      - mysql-dc-datavolume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8003:80
    environment:
      - PMA_ARBITRARY=1
  food-restaurant:
    build: ../food-restaurant
    depends_on:
      - mysql
    ports:
      - "8181:8080"
    environment:
      - ENVIRONMENT_APP=dce
  food-order:
    build:
      context: ../food-order
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT_APP=dce
        - ENVIRONMENT_PORT=5000
    depends_on:
      - mysql
      - food-restaurant
    ports:
      - "5000:5000"
  food-gateway:
    build: ../food-gateway
    depends_on:
      - food-restaurant
    ports:
      - "9090:8080"
    environment:
      - ENVIRONMENT_APP=dce
  food-ui-webapp:
    build: ../food-ui-webapp
    depends_on:
      - food-gateway
    ports:
      - "8080:8080"
    environment:
      - PROXY_ENV=dce
      - ENVIRONMENT_APP=dce

volumes:
  mysql-dc-datavolume:
