// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/gateway/restaurant_gateway.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/cezbatistao/food-platform/food-order/internal/app/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRestaurantGateway is a mock of RestaurantGateway interface.
type MockRestaurantGateway struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantGatewayMockRecorder
}

// MockRestaurantGatewayMockRecorder is the mock recorder for MockRestaurantGateway.
type MockRestaurantGatewayMockRecorder struct {
	mock *MockRestaurantGateway
}

// NewMockRestaurantGateway creates a new mock instance.
func NewMockRestaurantGateway(ctrl *gomock.Controller) *MockRestaurantGateway {
	mock := &MockRestaurantGateway{ctrl: ctrl}
	mock.recorder = &MockRestaurantGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurantGateway) EXPECT() *MockRestaurantGatewayMockRecorder {
	return m.recorder
}

// GetByUuid mocks base method.
func (m *MockRestaurantGateway) GetByUuid(restaurantUuid uuid.UUID) (*domain.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUuid", restaurantUuid)
	ret0, _ := ret[0].(*domain.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUuid indicates an expected call of GetByUuid.
func (mr *MockRestaurantGatewayMockRecorder) GetByUuid(restaurantUuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUuid", reflect.TypeOf((*MockRestaurantGateway)(nil).GetByUuid), restaurantUuid)
}

// GetDetailByUuid mocks base method.
func (m *MockRestaurantGateway) GetDetailByUuid(restaurantUuid uuid.UUID, menuItemsUuid *[]uuid.UUID) (*domain.RestaurantDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailByUuid", restaurantUuid, menuItemsUuid)
	ret0, _ := ret[0].(*domain.RestaurantDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailByUuid indicates an expected call of GetDetailByUuid.
func (mr *MockRestaurantGatewayMockRecorder) GetDetailByUuid(restaurantUuid, menuItemsUuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailByUuid", reflect.TypeOf((*MockRestaurantGateway)(nil).GetDetailByUuid), restaurantUuid, menuItemsUuid)
}
