server:
  port: 8183
  shutdown: graceful
  use-forward-headers: true
  forward-headers-strategy: framework

info:
  app:
    group: ${group}
    name: ${name}
    description: ${description}
    version: ${version}
    environment: \${spring.profiles.active}
  javaVendor: \${java.specification.vendor}

application:
  async:
    corePoolSize: 100

spring:
  application:
    name: \${info.app.name}
    description: \${info.app.description}
    version: \${info.app.version}
  thymeleaf:
    enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/review_db
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 10
      missing-topics-fatal: false
    consumer:
      group-id: food-review
      enableAutoCommit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.food.review.entrypoint.listener.resource
            value:
              default:
                type: com.food.review.gateway.kafka.resource.DataResource
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mongock:
  migration-scan-package:
    - com.food.review.config.mongock.migration
