version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_restaurant
      - MYSQL_ROOT_PASSWORD=root_passwd
      - MYSQL_USER=restaurant_user
      - MYSQL_PASSWORD=restaurant_passwd
    volumes:
      - mysql-restaurant-datavolume:/var/lib/mysql

volumes:
  mysql-restaurant-datavolume:
