apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "{{ .Values.IngressDomain }}"
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-svc
            port:
              number: {{ .Values.service.port }}
