apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-order
spec:
  selector:
    matchLabels:
      app: food-order
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: food-order
    spec:
      containers:
      - name: food-order
        image: cezbatistao/food-order:1.0.0-0
        env:
        - name: ENVIRONMENT_APP
          value: k8s
        - name: ASPNETCORE_ENVIRONMENT
          value: k8s
        - name: ASPNETCORE_URLS
          value: http://+:5000
        imagePullPolicy: Always
