service:
  type: ClusterIP
  port: 8080

image:
  repository: cezbatistao/food-order
  tag: latest
  pullPolicy: IfNotPresent
  livenessProbe:
    path: /actuator/health
    failureThreshold: 6
    initialDelaySeconds: 40
    periodSeconds: 30
    timeoutSeconds: 2
  readinessProbe:
    path: /actuator/health
    failureThreshold: 6
    initialDelaySeconds: 40
    periodSeconds: 30
    timeoutSeconds: 2

kafka-topic-creator:
  jobName: topic-creator-food-order
  helmHook: pre-install,pre-upgrade
  imagePullSecrets:
    - name: regcred

env:
- name: KUBERNETES_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: DATABASE_TABLENAME
  valueFrom:
    secretKeyRef:
      key: postgres.tablename
      name: food-order
- name: DATABASE_USERNAME
  valueFrom:
    secretKeyRef:
      key: postgres.username
      name: food-order
- name: DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      key: postgres.password
      name: food-order
