version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_order
      - MYSQL_ROOT_PASSWORD=root_passwd
      - MYSQL_USER=order_user
      - MYSQL_PASSWORD=order_passwd
    volumes:
      - mysql-order-datavolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8002:80
    environment:
      - PMA_ARBITRARY=1
  stubby:
    container_name: stubby_app
    build: ./stubby/
    volumes:
      - ./stubby:/mocks
    command: stubby -d /mocks/init.yml -s 8882 -t 7443 -a 8889 -w
    ports:
      - 8882:8882
      - 7443:7443
      - 8889:8889

volumes:
  mysql-order-datavolume:
