version: "3"

services:
  mongodb:
    image : mongo
    container_name: mongodb-review
    volumes:
      - mongodb-studies-datavolume:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongodb-studies-datavolume:
