version: "3"

services:
  mongodb:
    image : mongo:5.0.14
    container_name: mongodb-review
    volumes:
      - mongodb-studies-datavolume:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: zookeeper_local
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ~/data/zookeeper/data:/var/lib/zookeeper/data
      - ~/data/zookeeper/log:/var/lib/zookeeper/log
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka_local
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 2000000
    volumes:
      - ~/data/kafka/data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  mongodb-studies-datavolume:
