server:
  port: 9090
  servlet:
    context-path: /food

application:
  food-platform:
    restaurant-app:
      url: http://localhost:8181
    order-app:
      url: http://localhost:5000

info:
  app:
    group: ${group}
    name: ${name}
    description: ${description}
    version: ${version}
    environment: \${spring.profiles.active}
  javaVendor: \${java.specification.vendor}

spring:
  application:
    name: food-gateway
  cloud:
    gateway:
      routes:
        - id: food-restaurant-app
          uri: \${application.food-platform.restaurant-app.url}
          predicates:
            - Path=/food/restaurant/**
          filters:
            - RewritePath=/food/restaurant/(?<path>.*), /\$\\{path}
        - id: food-order-app
          uri: \${application.food-platform.restaurant-app.url}
          predicates:
            - Path=/food/order/**
          filters:
            - RewritePath=/food/order/(?<path>.*), /\$\\{path}

management:
  endpoints:
    web:
      exposure:
        include: info,health,gateway,metrics
