apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgres.tablename: {{ default "" .Values.database.tablename | b64enc | quote }}
  postgres.username: {{ default "" .Values.database.username | b64enc | quote }}
  postgres.password: {{ default "" .Values.database.password | b64enc | quote }}
