server:
  port: 8080

info:
  app:
    version: {{ .Values.image.tag }}

spring:
  datasource:
    url: jdbc:mysql://mysql-k8s:3306/${DATABASE_TABLENAME}?useSSL=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
