service:
  type: ClusterIP
  port: 8080

image:
  repository: cezbatistao/food-restaurant
  tag: latest
  pullPolicy: IfNotPresent
  livenessProbe:
    path: /actuator/health
    failureThreshold: 6
    initialDelaySeconds: 40
    periodSeconds: 30
    timeoutSeconds: 2
  readinessProbe:
    path: /actuator/health
    failureThreshold: 6
    initialDelaySeconds: 40
    periodSeconds: 30
    timeoutSeconds: 2

env:
- name: SPRING_APPLICATION_NAME
  value: food-restaurant
- name: KUBERNETES_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: DATABASE_TABLENAME
  valueFrom:
    secretKeyRef:
      key: mysql.tablename
      name: food-restaurant
- name: DATABASE_USERNAME
  valueFrom:
    secretKeyRef:
      key: mysql.username
      name: food-restaurant
- name: DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      key: mysql.password
      name: food-restaurant
