environment: minikube
profilesActive: k8s

hpaMinReplicas: 1
hpaMaxReplicas: 1

resourcesLimitsRequestsCpu: 250m
resourcesLimitsRequestsMemory: 1024Mi
resourcesLimitsCpu: 500m
resourcesLimitsMemory: 2048Mi

namespace: default

maxSurge: 1
maxUnavailable: 0

service:
  type: NodePort
  port: 8080
  nodePort: 30090
