FROM cypress/browsers:node12.16.2-chrome81-ff75

ENV CI=1

# set working directory
RUN mkdir /usr/src/app

WORKDIR /usr/src/app

ADD . /usr/src/app
COPY cypress-cte.json /usr/src/app/cypress.json

RUN npm i

ENV DOCKERIZE_VERSION v0.6.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \ 
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \ 
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \ 
    && ./node_modules/.bin/cypress verify