version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_dc_restaurant
      - MYSQL_ROOT_PASSWORD=root_dc_passwd
      - MYSQL_USER=restaurant_dc_user
      - MYSQL_PASSWORD=restaurant_dc_passwd
    volumes:
      - mysql-ds-datavolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8336:80
    environment:
      - PMA_ARBITRARY=1
  food-restaurant:
    build: ../food-restaurant
    depends_on:
      - mysql
    ports:
      - "8181:8080"
    environment:
      - ENVIRONMENT_APP=dce
  food-gateway:
    build: ../food-gateway
    depends_on:
      - food-restaurant
    ports:
      - "9090:8080"
    environment:
      - ENVIRONMENT_APP=dce
  food-ui-webapp:
    build: ../food-ui-webapp
    depends_on:
      - food-gateway
    ports:
      - "8080:8080"
    environment:
      - PROXY_ENV=dce
      - ENVIRONMENT_APP=dce

volumes:
  mysql-ds-datavolume:
