name: Publish food-gateway

on:
  push:
    branches:
      - main
    paths:
      - 'food-gateway/**'
      - '!food-gateway/artifacts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'food-gateway/**'
      - '!food-gateway/artifacts/**'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      VERSION: ${{ github.run_number }}
      SHA_VERSION: ${{ github.sha }}

    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run tests
        working-directory: ./food-gateway
        run: ./gradlew clean test

      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'build/test-results/test/TEST-*.xml'
          reporter: java-junit
          working-directory: './food-gateway'

      - name: Build application
        working-directory: ./food-gateway
        run: ./gradlew clean build -x test -Pbuild.number=$VERSION

      - name: Build docker image
        working-directory: ./food-gateway
        run: ./gradlew docker -Pbuild.number=$VERSION

      - name: Docker hub login
        working-directory: ./food-gateway
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Tag docker image
        working-directory: ./food-gateway
        run: ./gradlew dockerTagDockerHub -Pbuild.number=$VERSION

      - name: Push docker image
        working-directory: ./food-gateway
        run: ./gradlew dockerPushDockerHub -Pbuild.number=$VERSION

      - name: Docker hub logout
        working-directory: ./food-gateway
        run: |
          docker logout
